-- 0001c: RLS policies and triggers for the tables in 0001a. GENERATED from the schema CSV.
-- Run AFTER all functions exist (16, 17, and the exported functions).

drop policy if exists "Users can view their own AI actions" on public.ai_actions;
create policy "Users can view their own AI actions" on public.ai_actions for select to authenticated using ((user_id = auth.uid()));
drop policy if exists "Team can view battery_claims" on public.battery_claims;
create policy "Team can view battery_claims" on public.battery_claims for select to authenticated using ((( SELECT current_app_role() AS current_app_role) IS NOT NULL));
drop policy if exists "Team can view cash_settings" on public.cash_settings;
create policy "Team can view cash_settings" on public.cash_settings for select to authenticated using ((( SELECT current_app_role() AS current_app_role) = ANY (ARRAY['owner'::text, 'accountant'::text])));
drop policy if exists "Team can view charging_jobs" on public.charging_jobs;
create policy "Team can view charging_jobs" on public.charging_jobs for select to authenticated using ((( SELECT current_app_role() AS current_app_role) IS NOT NULL));
drop policy if exists "Team can view charging prices" on public.charging_price_list;
create policy "Team can view charging prices" on public.charging_price_list for select to authenticated using ((( SELECT current_app_role() AS current_app_role) IS NOT NULL));
drop policy if exists "Owner can edit charging prices" on public.charging_price_list;
create policy "Owner can edit charging prices" on public.charging_price_list for update to authenticated using ((( SELECT current_app_role() AS current_app_role) = 'owner'::text)) with check ((( SELECT current_app_role() AS current_app_role) = 'owner'::text));
drop policy if exists "Owner can delete charging prices" on public.charging_price_list;
create policy "Owner can delete charging prices" on public.charging_price_list for delete to authenticated using ((( SELECT current_app_role() AS current_app_role) = 'owner'::text));
drop policy if exists "Owner can add charging prices" on public.charging_price_list;
create policy "Owner can add charging prices" on public.charging_price_list for insert to authenticated with check ((( SELECT current_app_role() AS current_app_role) = 'owner'::text));
drop policy if exists "Signed-in users can edit distributors" on public.distributors;
create policy "Signed-in users can edit distributors" on public.distributors for update to authenticated using (true) with check (true);
drop policy if exists "Signed-in users can add distributors" on public.distributors;
create policy "Signed-in users can add distributors" on public.distributors for insert to authenticated with check (true);
drop policy if exists "Team can view distributors" on public.distributors;
create policy "Team can view distributors" on public.distributors for select to authenticated using ((( SELECT current_app_role() AS current_app_role) IS NOT NULL));
drop policy if exists "Team can view expense_categories" on public.expense_categories;
create policy "Team can view expense_categories" on public.expense_categories for select to authenticated using ((( SELECT current_app_role() AS current_app_role) IS NOT NULL));
drop policy if exists "Team can view expenses" on public.expenses;
create policy "Team can view expenses" on public.expenses for select to authenticated using ((( SELECT current_app_role() AS current_app_role) = ANY (ARRAY['owner'::text, 'accountant'::text])));
drop policy if exists "Team can view scrap_battery_inventory" on public.scrap_battery_inventory;
create policy "Team can view scrap_battery_inventory" on public.scrap_battery_inventory for select to authenticated using ((( SELECT current_app_role() AS current_app_role) IS NOT NULL));
drop policy if exists "Team can view scrap_battery_sales" on public.scrap_battery_sales;
create policy "Team can view scrap_battery_sales" on public.scrap_battery_sales for select to authenticated using ((( SELECT current_app_role() AS current_app_role) IS NOT NULL));

drop trigger if exists aa_role_guard on public.battery_claims;
create trigger aa_role_guard BEFORE DELETE OR INSERT OR UPDATE on public.battery_claims for each row EXECUTE FUNCTION role_guard('owner,counter_staff', 'owner,counter_staff', 'owner');
drop trigger if exists zz_audit_row_change on public.battery_claims;
create trigger zz_audit_row_change AFTER INSERT OR DELETE OR UPDATE on public.battery_claims for each row EXECUTE FUNCTION audit_row_change();
drop trigger if exists battery_claims_set_updated_at on public.battery_claims;
create trigger battery_claims_set_updated_at BEFORE UPDATE on public.battery_claims for each row EXECUTE FUNCTION set_updated_at();
drop trigger if exists aa_role_guard on public.cash_settings;
create trigger aa_role_guard BEFORE DELETE OR UPDATE OR INSERT on public.cash_settings for each row EXECUTE FUNCTION role_guard('owner,accountant', 'owner,accountant', 'owner');
drop trigger if exists zz_audit_row_change on public.cash_settings;
create trigger zz_audit_row_change AFTER UPDATE OR DELETE OR INSERT on public.cash_settings for each row EXECUTE FUNCTION audit_row_change();
drop trigger if exists cash_settings_set_updated_at on public.cash_settings;
create trigger cash_settings_set_updated_at BEFORE UPDATE on public.cash_settings for each row EXECUTE FUNCTION set_updated_at();
drop trigger if exists aa_role_guard on public.charging_jobs;
create trigger aa_role_guard BEFORE DELETE OR INSERT OR UPDATE on public.charging_jobs for each row EXECUTE FUNCTION role_guard('owner,counter_staff', 'owner,counter_staff', 'owner');
drop trigger if exists zz_audit_row_change on public.charging_jobs;
create trigger zz_audit_row_change AFTER UPDATE OR DELETE OR INSERT on public.charging_jobs for each row EXECUTE FUNCTION audit_row_change();
drop trigger if exists charging_jobs_set_updated_at on public.charging_jobs;
create trigger charging_jobs_set_updated_at BEFORE UPDATE on public.charging_jobs for each row EXECUTE FUNCTION set_updated_at();
drop trigger if exists zz_audit_row_change on public.charging_price_list;
create trigger zz_audit_row_change AFTER DELETE OR INSERT OR UPDATE on public.charging_price_list for each row EXECUTE FUNCTION audit_row_change();
drop trigger if exists charging_price_list_set_updated_at on public.charging_price_list;
create trigger charging_price_list_set_updated_at BEFORE UPDATE on public.charging_price_list for each row EXECUTE FUNCTION set_updated_at();
drop trigger if exists zz_audit_row_change on public.distributors;
create trigger zz_audit_row_change AFTER UPDATE OR DELETE OR INSERT on public.distributors for each row EXECUTE FUNCTION audit_row_change();
drop trigger if exists distributors_set_updated_at on public.distributors;
create trigger distributors_set_updated_at BEFORE UPDATE on public.distributors for each row EXECUTE FUNCTION set_updated_at();
drop trigger if exists aa_role_guard on public.distributors;
create trigger aa_role_guard BEFORE UPDATE OR DELETE OR INSERT on public.distributors for each row EXECUTE FUNCTION role_guard('owner,counter_staff', 'owner', 'owner');
drop trigger if exists zz_audit_row_change on public.expenses;
create trigger zz_audit_row_change AFTER DELETE OR INSERT OR UPDATE on public.expenses for each row EXECUTE FUNCTION audit_row_change();
drop trigger if exists expenses_set_updated_at on public.expenses;
create trigger expenses_set_updated_at BEFORE UPDATE on public.expenses for each row EXECUTE FUNCTION set_updated_at();
drop trigger if exists aa_role_guard on public.expenses;
create trigger aa_role_guard BEFORE INSERT OR DELETE OR UPDATE on public.expenses for each row EXECUTE FUNCTION role_guard('owner,accountant', 'owner,accountant', 'owner');
drop trigger if exists scrap_battery_inventory_set_updated_at on public.scrap_battery_inventory;
create trigger scrap_battery_inventory_set_updated_at BEFORE UPDATE on public.scrap_battery_inventory for each row EXECUTE FUNCTION set_updated_at();
drop trigger if exists zz_audit_row_change on public.scrap_battery_inventory;
create trigger zz_audit_row_change AFTER INSERT OR DELETE OR UPDATE on public.scrap_battery_inventory for each row EXECUTE FUNCTION audit_row_change();
drop trigger if exists aa_role_guard on public.scrap_battery_inventory;
create trigger aa_role_guard BEFORE INSERT OR DELETE OR UPDATE on public.scrap_battery_inventory for each row EXECUTE FUNCTION role_guard('owner,counter_staff', 'owner,counter_staff', 'owner');
drop trigger if exists aa_role_guard on public.scrap_battery_sales;
create trigger aa_role_guard BEFORE DELETE OR UPDATE OR INSERT on public.scrap_battery_sales for each row EXECUTE FUNCTION role_guard('owner', 'owner', 'owner');
drop trigger if exists zz_audit_row_change on public.scrap_battery_sales;
create trigger zz_audit_row_change AFTER INSERT OR UPDATE OR DELETE on public.scrap_battery_sales for each row EXECUTE FUNCTION audit_row_change();
